function z=psi2_xx(x,y,k,lambda)
z=((1./x-(lambda^2-k^2)*x).*besselj(1,x*sqrt(lambda^2-k^2))...
    +1/2*sqrt(lambda^2-k^2)./x.*(besselj(0,x*sqrt(lambda^2-k^2))...
    -besselj(2,x*sqrt(lambda^2-k^2)))).*cos(k*y);