function z=psi9_xx(x,y,k,lambda)
z=((1./x-(lambda^2-k^2)*x).*bessely(1,x*sqrt(lambda^2-k^2))...
    +1/2*sqrt(lambda^2-k^2)./x.*(bessely(0,x*sqrt(lambda^2-k^2))...
    -bessely(2,x*sqrt(lambda^2-k^2)))).*sin(k*y);